# Generated by Django 3.2.4 on 2021-11-04 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=30)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('cover_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('T', 'To Read'), ('R', 'Reading'), ('H', 'Have Read')], max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ManyToManyField(through='main.ReadingStatus', to=settings.AUTH_USER_MODEL),
        ),
    ]
