# Generated by Django 3.2.4 on 2021-11-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211115_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingprogress',
            name='read_year',
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='year_goal',
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
